# Discussion

In this study, we explored the feasibility of using EEG to study network variants by examining whether or not EEG phase coupling and amplitude coupling functional connectomes showed similar evidence of stable individual differences across contexts to what has been described in the fMRI literature. To address this question, we used pairwise contrasts to estimate how much and in which ways functional connectome similarity differed within and between individuals across sessions and states, using eyes open and eyes closed resting state EEG data collected across three sessions over the course of approximately three months. Based on the findings of previous fMRI network variant research [e.g., @grattonetal_FunctionalBrainNetworks_2018; @seitzmanetal_TraitlikeVariantsHuman_2019], we hypothesized that functional connectomes would be more similar within than between individuals across all contrasts, on average, with smaller variations in similarity related to session or state (see Figure \@ref(fig:outcome-plot)). <!-- We had no expectations regarding the possible range of effect sizes we could find, but again note that relatively higher values corresponded to greater within-individual functional connectome stability and between-individual differentiation across contexts; whereas relatively lower values corresponded to lesser within-individual functional connectome stability and between-individual differentiation. However, to contextualize our results against the relevant fMRI literature, we considered the results of @grattonetal_FunctionalBrainNetworks_2018 as a cautious point of reference---who found positive differences of approximately 0.2 and 0.3 points for shorter and longer fMRI scanning times, respectively---keeping in mind that finding equivalent effect sizes would be surprising, given the differences in measurement, design, and analysis between our studies, on top of random variation in the data between our samples. -->

Overall, our results were inconclusive. In support of our primary scientific hypothesis, the group-level effect sizes most compatible with our data, given the background model, showed that, on average, both phase coupling and amplitude coupling functional connectomes were more similar within than between individuals across contexts and frequency bands (Figures \@ref(fig:phase-similarity-plots-delta)-\@ref(fig:amplitude-similarity-plots-alpha)); that our data was incompatible with a model that assumed zero difference in functional connectome similarity within and between individuals across contexts (Tables \@ref(tab:phase-similarity-table-delta)-\@ref(tab:amplitude-similarity-table-alpha)); and that these differences were attributable to individual-dependent factors with small modulations by session and state (Tables \@ref(tab:phase-similarity-table-delta)-\@ref(tab:amplitude-similarity-table-alpha)). Moreover, the magnitude of these differences varied across contexts in an expected way, with the largest differences in similarity within and between individuals occurring for functional connectomes from the same sessions and states, the smallest differences occurring for functional connectomes from the different sessions and states, and relatively smaller increases and decreases in similarity across other contexts. At this level of description, our results were broadly consistent with the findings of methodologically similar fMRI studies [e.g., @grattonetal_FunctionalBrainNetworks_2018]. These results remained largely consistent for phase coupling functional connectomes when the phase lag index was estimated using the Hilbert transform method instead of the the multitaper method (Figures A\@ref(fig:phase-similarity-plots-hilbert-delta)-A\@ref(fig:phase-similarity-plots-hilbert-gamma)); and with few exceptions, these results were consistent between the reduced and maximal models of functional connectome similarity for both both phase coupling and amplitude coupling functional connectomes (Figures A\@ref(fig:phase-similarity-plots-maximal-theta)-A\@ref(fig:amplitude-similarity-plots-maximal-alpha)).

However, in general, the group-level effect sizes most compatible with our data, given the background model, ranged from practically nil to at most small, depending on the contrast, coupling mode, and frequency band in question (Figures \@ref(fig:phase-similarity-plots-delta)-\@ref(fig:amplitude-similarity-plots-alpha)). Thus, although our results suggested that, on average, the phase coupling and amplitude coupling dynamics of underlying global network activity in each frequency band was differentiated between individuals across contexts *in our sample*, the influence of individual-dependent factors over and above the influence of stable group-dependent factors was either negligible or at best small. This is a clear departure from what has been described in the fMRI literature, where differences in functional connectome similarity within and between individuals have been reported to be stable, relatively large, and visually obvious, indicative of "a clear influence of individual features over and above common organizational principles at the network level," [@mareketal_SpatialTemporalOrganization_2018] such that fMRI functional connectomes may be well-suited for measuring and identifying the neural causes of variation in human behaviour, cognition, and their dysfunction [@grattonetal_FunctionalBrainNetworks_2018]. Our results do not inspire such confidence, and given the inherent limitations of EEG functional connectivity analysis, it is unclear to what extent they reflect genuinely small interindividual differences in electrophysiological connectivity across contexts, versus methodological limitations, selection bias, or random variation in our sample that may have caused us to underestimate or overestimate the magnitude of interindividual differences relative to the (unknown) true effect(s).

Finally, we note that although the the group-level effect sizes most compatible with our data, given the background model, more similar within than between individuals, on average, this relationship was not necessarily true for all participants. Indeed, there was a notable degree of outcome variability in the direction (Figure \@ref(fig:subset-similarity-contrast-barplot)) and magnitude (for reduced models, see Figures A\@ref(fig:phase-similarity-subset-plots-delta)-A\@ref(fig:amplitude-similarity-subset-plots-alpha); for maximal models, see Figures A\@ref(fig:phase-similarity-plots-maximal-theta)-A\@ref(fig:amplitude-similarity-plots-maximal-alpha)) of these effects when differences in functional connectome similarity were analyzed at an individual-level. These results were also a clear departure from what has been described in the fMRI literature, where differences in functional connectome similarity within and between individuals has been found to be consistently positive at an individual-level, with relatively little outcome variability in the magnitude of these differences [@grattonetal_FunctionalBrainNetworks_2018]. Moreover, because of the outcome variability in our sample, we caution against confusing the positive and precise estimates of average effects for the group-level contrasts with the predictability of individual outcomes, which were more variable in both their direction and magnitude. However, equally, we also caution against confusing the individual-level contrasts whose direction was unresolved with precise zero effects or evidence of no positive difference in functional connectome similarity. For many of these contrasts, the effect sizes most compatible with our data, given the background model, included a range of effects that---although generally still at most small---were not negligible; thus, even though they leave open the possibility of negative, zero, or positive but negligible effects, they also leave open the possibility of small effects that may be worth investigating further.

Considered together, given the background model used to investigate our research question, our results did not generally demonstrate the feasibility of using EEG to study network variants due to the inconsistencies observed across participants in our sample. At best our findings leave open the possibility that EEG functional connectomes may be suitable measures of stable individual differences in whole brain functional network organization, given that both the group-level results and a subset of individual-level results showed consistently positive differences in functional connectome similarity within versus between individuals across contexts and frequency bands; however, equally, it is apparent that if the phase coupling and/or amplitude coupling dynamics of underlying global network activity across frequency bands are indeed influenced by stable individual-dependent factors, further work identifying and developing methods to reliably measure and quantify these stable individual differences is necessary.

## Differences between phase and amplitude coupling

<!-- TODO: Revise section and consider moving it down -->

Across all frequency bands, we found that functional connectivity estimated with the orthogonalized amplitude envelope correlation was generally weaker than with the phase lag index. This difference has also been previously found by @fraschinietal_RobustnessFunctionalConnectivity_2019, who tested the robustness of several functional connectivity metrics for biometric person identification [for a review of EEG biometrics, see @chanetal_ChallengesFuturePerspectives_2018]. Given that the phase lag index and orthogonalized amplitude envelope correlation measure different aspects of functional connectivity, we expected them to differ [@engeletal_IntrinsicCouplingModes_2013]. However, we also note that this difference is likely partially due to differences in the frequency specificity of the two methods, with the phase lag index having greater specificity than the orthogonalized amplitude envelope correlation. This difference in frequency specificity is attributable to the phase lag index being estimated and averaged over multiple frequency bins in each frequency band when using the multitaper method, versus the orthogonalized amplitude envelope correlation being estimated with a single analytic signal in each frequency band when using the Hilbert transform method. In Figures A\@ref(fig:phase-similarity-plots-hilbert-delta)-A\@ref(fig:phase-similarity-plots-hilbert-gamma) in Appendix A we show how the results change when the phase lag index is estimated using the Hilbert transform method. Across all five frequency bands we found that (1) functional connectivity was generally lower than we found with the multitaper method, but individual patterns of connectivity were similar or the same; and (2) functional connectome similarity was generally higher than we found with the multitaper method, but patterns of similarity and contrast effect sizes were similar or the same. Thus, although these changes were not great enough to change our conclusions, they did make the differences observed between the phase lag index and orthogonalized amplitude envelope correlation results less stark, and highlight how different spectral analysis methods can influence functional connectivity estimates if analysis parameters cannot be matched [cf. @bruns_FourierHilbertWaveletbased_2004].

Another factor possibly contributing to the differences observed between the phase lag index and orthogonalized amplitude envelope correlation was the effect of epoch length on the two methods. @fraschinietal_EffectEpochLength_2016 compared the effect of non-overlapping epochs with variable length (1, 2, 4, 6, 8, 10, 12, 14 and 16 seconds) on broadband (1-20 Hz) functional connectivity estimates in a small sample of middle-aged adults during resting eyes-closed resting state. They found that group-level mean functional connectivity was higher for the phase lag index than the orthogonalized amplitude envelope correlation at 1-6 second long epochs, with more comparable estimates between the two methods with 8-16 second long epochs. They also found that group-level mean functional connectivity decreased as a function of epoch length, with the phase lag index and orthogonalized amplitude envelope correlation stabilizing at 12 and 6 second long epochs, respectively. Because Fraschini et al.'s [-@fraschinietal_EffectEpochLength_2016] results were based on broadband group-level mean functional connectivity, they are not directly comparable to our own findings; however, they do highlight how preprocessing decisions can (differentially) influence functional connectivity estimates. In the context of our study, we emphasize the need for future work to explore how preprocessing decisions can influence individual-level functional connectivity and network similarity estimates, with a focus on identifying approaches that can achieve both high within-individual and low between-individual functional connectome similarity.

## Consistency with related neurophysiological connectomics literature

As we noted in the results section, both our phase coupling and amplitude coupling functional connectivity analyses performed as expected based on what has been reported in previous work using the phase lag index and orthogonalized amplitude envelope correlation with resting state EEG; thus, we assumed that our estimates were able to provide a sound representation of underlying (non-zero lag) global network activity for each participant and coupling mode. Specifically, consistent with previous work, we found (1) a high level of spatial correspondence between phase coupling and amplitude coupling functional connectomes (Figure \@ref(fig:illustrative-connectomes-figure)) [@mostamesadaghiani_PhaseAmplitudecouplingAre_2020]; (2) typical distributions of coupling magnitudes in each frequency band for both coupling modes that were right-skewed with a small mean and wide range (Figure \@ref(fig:connectivity-histograms-figure)) [@fraschinietal_RobustnessFunctionalConnectivity_2019; @laietal_ComparisonScalpSourcereconstructed_2018; @mehrkanoonetal_IntrinsicCouplingModes_2014]; and (3) a clear frequency band response was observed for both coupling modes (Figure \@ref(fig:connectivity-histograms-figure)), with the strongest coupling occurring in the alpha band for both the phase lag index [@hardmeieretal_ReproducibilityFunctionalConnectivity_2014; @mehrkanoonetal_IntrinsicCouplingModes_2014; @vandermolenetal_RestingStateEEGOscillatory_2014] and the orthogonalized amplitude envelope correlation [@hippetal_LargescaleCorticalCorrelation_2012; @mehrkanoonetal_IntrinsicCouplingModes_2014; @samoginetal_FrequencyDependentFunctional_2020; @samoginetal_AgeRelatedDifferencesFrequencyDependent_2022; @tabernaetal_DetectionRestingStateFunctional_2021].

Notably, the prominence of alpha band functional connectivity coincided with the strongest differences in functional connectome similarity within versus between individuals observed in our study (Figure \@ref(fig:phase-similarity-plots-alpha)C), which may indicate that EEG network variants are more sensitive to brain state than fMRI network variants [cf. @grattonetal_FunctionalBrainNetworks_2018], given the well-documented relationship between brain state, dominant oscillation frequency, and coupling strength observed with neurophysiological recording methods. From this perspective, the clear frequency band response in our results may be unsurprising, as alpha oscillations are the most dominant rhythm during resting state and are known to play a prominent role in intrinsic connectivity networks [@mantinietal_ElectrophysiologicalSignaturesResting_2007; @marinoetal_HemodynamicCorrelatesElectrophysiological_2019; @sadaghianikleinschmidt_BrainNetworksAOscillations_2016; @samoginetal_FrequencyDependentFunctional_2020]. In support of this point, although we found that the relative strength of both within individual and between individual similarities generally shifted in the same direction from one frequency band to another, the magnitude of group-level differences in phase coupling functional connectome similarity within versus between individuals was not equivalent across frequency bands, indicating that functional connectomes became less or more differentiated between individuals as a function of frequency band.

Furthermore, the pattern of group-level contrast results for phase coupling functional connectome similarities in the alpha band (Figure \@ref(fig:phase-similarity-plots-alpha)C) appeared to be influenced more by an individual-state effect than an individual-session effect (Figure \@ref(fig:outcome-plot), fourth plot); whereas (although subtle) the delta, theta, beta, and gamma bands (Figures \@ref(fig:phase-similarity-plots-delta)C, \@ref(fig:phase-similarity-plots-theta)C, \@ref(fig:phase-similarity-plots-beta)C, \@ref(fig:phase-similarity-plots-gamma)C) appeared to be influenced more by an individual-session effect than an individual-state effect (Figure \@ref(fig:outcome-plot), third plot). Although we did not predict this outcome, it may also be unsurprising, given that the typical widespread reduction in alpha band oscillations between eyes-closed and eyes-open resting state and associated changes in functional connectivity would be expected to produce such a pattern of results given that, within individuals, functional connectomes would be noticeably dissimilar between these states, on average, but similar within them; whereas the more subtle differences between eyes-closed and eyes-open resting state for other frequency bands would be less likely to produce such noticeable changes. 

Our results are also conceptually consistent with a recent study by @nentwichetal_FunctionalConnectivityEEG_2020, who investigated the relationship between twelve phenotypic variables (age, sex, socioeconomic status, intelligence, and diagnostic assessments for sleep disturbance, behavioural and emotional problems, attention-deficit/hyperactivity disorder, anxiety, inattention, mood, internet addiction, distress tolerance) and phase coupling functional connectome similarities in a large sample of typically and atypically developing children and adolescents during resting in the delta, theta, alpha, and beta bands. They found that all twelve variables were unable to explain variation in functional connectome similarities between and among individuals in the delta, theta, alpha, and beta bands; with the exception of sex and age in the beta band. Although our study did not examine the relationship between any variables of interest and functional connectome similarity, the findings of @nentwichetal_FunctionalConnectivityEEG_2020 indicate---similar to our findings---that (1) functional connectomes may become more differentiated between individuals as a function of frequency band, given they only found phenotype-connectome relationships in the beta band; and (2) network variants may be harder to detect with EEG. Regarding the latter point, @nentwichetal_FunctionalConnectivityEEG_2020 also investigated the relationship between the aforementioned twelve variables and fMRI functional connectome similarities in the same sample. Here they found that four variables (age, sex, intelligence, and the assessment for behavioural and emotional problems) were able to explain variation in functional connectome similarities between and among individuals, suggesting that fMRI functional connectomes may better capture practically relevant information compared to EEG.

Finally, the smaller variations in within-individual functional connectome similarity across sessions and states observed in our sample were also consistent with previous EEG [@nentwichetal_FunctionalConnectivityEEG_2020], electrocorticography [ECoG\; @mostamesadaghiani_OscillationBasedConnectivityArchitecture_2021], and magnetoencephalography [MEG\; @colcloughetal_HowReliableAre_2016] research, which found that phase coupling and amplitude coupling functional connectomes were generally stable within individuals, showing moderate to high similarity within and between sessions and states across frequency bands. Additionally, in agreement with @colcloughetal_HowReliableAre_2016, we found that within-individual functional connectome similarity was generally higher when functional connectivity was estimated with the orthogonalized amplitude envelope correlation than with the phase lag index.

## Factors that may contribute to differences between EEG and fMRI

Factors that could explain the differences between our findings and what has been reported in the fMRI literature are the spatial and temporal resolutions of the two modalities, and the methods used to estimate functional connectivity. 

Network variants are likely sensitive to the spatial resolution of the neuroimaging system used to study them, as this influences the precision with which individual differences in functional connectivity can be measured. For EEG, the number of electrodes and distance between them determines spatial resolution, with higher electrode density corresponding to higher spatial resolution [@ferreeetal_SpatialResolutionScalp_2001; @robinsonetal_VeryHighDensity_2017; @ryynanenetal_EffectElectrodeDensity_2004; @ryynanenetal_EffectMeasurementNoise_2006]. With low electrode density, as in the 10-20 system, EEG typically has a spatial resolution of approximately 5 to 9 centimetres [@burleetal_SpatialTemporalResolutions_2015; @srinivasanetal_EstimatingSpatialNyquist_1998]. Higher density EEG systems can achieve a spatial resolution of up to 1 to 2 centimetres, but this still falls short of the spatial resolution of fMRI, which typically ranges from 500 microns to 4 millimetres [@glover_OverviewFunctionalMagnetic_2011]. Because EEG functional connectomes are naturally spatially blurrier than fMRI functional connectomes, network variants may be harder to detect or less pronounced in EEG, leading to smaller, less consistent, differences in functional connectome similarity within versus between individuals.[^9] Future work might address this possibility either by testing how individual differences in functional connectome similarity vary as a function of electrode density, or by using simultaneous EEG and fMRI [@mulert_SimultaneousEEGFMRI_2013] to compare the strength and consistency of network variants between the two modalities in the same sample.

<!-- The ability to detect network variants may be more strongly associated with spatial resolution. Although EEG has sufficient spatial resolution for the purposes of person identification and recognition—colloquially referred to as functional connectome fingerprinting—it may not have adequate spatial resolution to detect differences in functional connectome similarity as large as with fMRI.  -->
<!-- measures of electrophysiological connectivity show spatial similarity to the functional connectivity commonly observed with fMRI regardless of timescale [@danielarzate-menaetal_StationaryEEGPattern_2022; @sadaghianiwirsich_IntrinsicConnectomeOrganization_2020]. -->
<!-- This is further complicated by the relationship between the size of neural populations in different frequency bands. @vonsteinsarnthein_DifferentFrequenciesDifferent_2000; @capillaetal_NaturalFrequenciesResting_2022 -->

<!-- Network variants are likely sensitive to the number of sites or electrodes used when estimating functional connectivity, as this influences spatial resolution and restricts the number of data points that can be used to compare any two functional connectomes. For example, with a small number of electrodes there may not be a sufficient number of points in a functional connectome to adequately differentiate between individuals, resulting in between individual similarity being overstated. We assumed that our EEG system had a sufficient electrode density for studying network variants; however, fMRI studies typically use a much higher number of sites, for example @grattonetal_FunctionalBrainNetworks_2018 used a 333 site cortical parcellation, which allow for more precise depictions of the functional connectome. For this reason, higher density EEG systems (e.g., 128, 256, or 512 electrodes) may be better-equipped to study network variants [cf. @ferreeetal_SpatialResolutionScalp_2001; @robinsonetal_VeryHighDensity_2017; @ryynanenetal_EffectElectrodeDensity_2004; @ryynanenetal_EffectMeasurementNoise_2006]. -->

Network variants are also likely sensitive to the methods used to estimate functional connectivity. There are two assumptions related to this that are important to consider when evaluating our results, and which may be worth investigating in future research. First, we assumed that five minute recordings would be sufficient to get stable functional connectivity estimates with EEG given that (1) the longer scanning times needed to reliably detect network variants with fMRI is related to its low sampling rate [@seitzmanetal_TraitlikeVariantsHuman_2019], and not to the actual timeframe at which neural processes occur; and (2) EEG samples a substantially larger number of time points than fMRI in a much shorter timeframe. Because we found that functional connectomes were generally stable within individuals, showing moderate to high similarity within and between sessions and states across timescales, we believe this assumption was justified. However, we do note that longer recordings have been found to improve the stability of fMRI functional connectivity estimates in a qualitatively distinct way from higher sampling rates [@birnetal_EffectScanLength_2013], likely due to slow network changes being more fully captured by longer recordings. Future work may benefit from testing if the stability of EEG functional connectivity estimates gain a similar improvement from longer recordings, particularly at slower timescales such as the delta band.

Second, we assumed that network variants could be observed when considering only phase and amplitude coupling with non-zero lag, discounting the true zero-lag coupling that occurs in functional networks. However, this discounting leads to an underestimation of true connectivity for both the phase lag index and amplitude envelope correlation by a non-trivial amount [@hippetal_LargescaleCorticalCorrelation_2012; @stametal_PhaseLagIndex_2007], and might also remove or attenuate individual-specific features of the functional connectome [@fraschinietal_RobustnessFunctionalConnectivity_2019]. Given that we generally found the strongest similarities between functional connectomes with homogeneously low patterns of coupling, non-zero lag phase and amplitude coupling methods may not be feasible for studying network variants at timescales where coupling is expected to be generally lower for a given state or task. The most extreme examples of this in our study were with amplitude coupling functional connectomes in the delta, theta, beta, and gamma bands, where we found that surprisingly high similarity within and between individuals was associated with functional connectomes with surprisingly low coupling across sensors for all connectomes. Because of the homogeneously low patterns of coupling, we would argue that these cases of high similarity are not particularly interesting, and should likely be treated as a methodological artifact. <!-- TODO: revise this -->

One potential solution to avoid homogeneously low patterns of coupling would be to use phase and amplitude coupling methods that include zero-lag coupling---supplemented with tests against volume conduction [@cohen_AnalyzingNeuralTime_2014]. However, this approach is impractical for EEG connectomics research since it requires inspecting hundreds of thousands of individual connections to rule out possible contamination by volume conduction. Another potential solution would be to use non-zero lag coupling methods that might underestimate true connectivity by a lesser amount, such as the weighted phase lag index [@vincketal_ImprovedIndexPhasesynchronization_2011] for phase coupling. We are not aware of an equivalent weighted non-zero lag method for amplitude coupling. For future work, this may mean that in cases where it is impractical to estimate zero-lag amplitude coupling with tests against volume conduction, it may be better not to use amplitude coupling methods at all. Regardless, the spatial mixing caused by volume conduction poses a difficult problem, and future work may benefit from testing the robustness of different functional connectivity methods for studying network variants with EEG [for a related example using magnetoencephalography, see @colcloughetal_HowReliableAre_2016].

<!-- TALK ABOUT GRADIENTS AND HOW CERTAIN FREQUENCY BANDS ARE LINKD TO CERTAIN BRAIN AREAS -->

<!-- Source reconstruction -->

<!-- This can be addressed either through source reconstruction methods, which attempt to unmix measured signals to estimate the location of the underlying neural sources; or by using connectivity metrics that account for the effects of field spread and volume conduction in the head, which reduce the possibility of spurious coupling between channels from influencing functional connectivity estimates [@bastosschoffelen_TutorialReviewFunctional_2016]. -->

<!-- "future works should investigate if the results reported so far at scalp level still hold when the EEG signals are reconstructed (by resolving the inverse problem) at source level where the effects due to spurious connections are, at least in part, attenuated [23]" 54 M. Fraschini, S.M. Pani and L. Didaci et al. / Pattern Recognition Letters 125 (2019) 49–54" -->

<!-- Discuss RV coefficient vs. pearson correlation -->

## Limitations

In addition to the discussion above, the following methodological and statistical assumptions are important to consider when evaluating our results.

First, it is unclear how our results might generalize to more diverse samples. In particular, our participants were healthy young adults in their twenties sampled from a western, educated, industrialized, rich, and democratic population, who have been shown to be outliers on a number of behavioural and cognitive measures in comparison with the rest of the human population [@henrichetal_WeirdestPeopleWorld_2010]. Differences in in functional connectivity have been found with ageing [e.g., @samoginetal_AgeRelatedDifferencesFrequencyDependent_2022], neurological disease or disorder [e.g., @engelsetal_DecliningFunctionalConnectivity_2015], mental illnesses such as depression [e.g., @shimetal_AlteredCorticalFunctional_2018], head trauma [e.g., @caoslobounov_AlterationCorticalFunctional_2010], and alcoholism [e.g., @caoetal_DisturbedConnectivityEEG_2014]; thus, it might be reasonable to expect that our exclusion criteria removed meaningful variation from our sample. Additionally, given the size of our sample, and the inconsistencies we observed across participants, we would also caution against generalizing our results to samples with similar characteristics. At most we might conclude that---if network variants can be reliably detected with EEG---there is no guarantee that their presence can be detected in a given individual or data set, given the background models used to estimate functional connectivity and test for their presence.

Second, we assumed that the connectivity structure in each frequency band was stationary over the length of the recording for both phase and amplitude coupling functional connectomes. Although neural oscillations are naturally non-stationary, varying from moment to moment [@faisaletal_NoiseNervousSystem_2008], stationary patterns of functional connectivity during resting state have been identified in EEG [e.g., @olguin-rodriguezetal_CharacteristicFluctuationsStable_2018], fMRI [e.g., @laumannetal_StabilityBOLDFMRI_2017], and simultaneous EEG-fMRI studies [e.g., @danielarzate-menaetal_StationaryEEGPattern_2022], with consistent positive or negative coupling occurring between sites or electrodes, even when averaging over multiple epochs. These stationary patterns are thought to be the substrate for effective brain function, permitting the adaptability and efficiency needed to optimize responses to our often unpredictable environment [@garrettetal_MomenttomomentBrainSignal_2013], and thus reflect neuropsychologically relevant signals of interest. However, we do note that approaches accounting for nonlinear dynamics may provide complimentary insights to those that focus on the stable aspects of network variants. For example, @vandevilleetal_WhenMakesYou_2021 found that fMRI functional connectomes exhibit short transient bursts of uniqueness even at short time windows, with different resting state networks becoming more or less unique between individuals as a function of time window length, suggesting that the dynamic aspects of network variants are worth exploring.

Third, we limited our investigation to within-frequency analyses of functional connectivity and network similarity. Although cross-frequency coupling is also considered to be a key mechanism by which the brain transmits and processes information, integrating functional systems across multiple spatiotemporal scales [@canoltyknight_FunctionalRoleCrossfrequency_2010], we did not explore for the presence of network variants in cross-frequency coupling functional connectomes given that most research on cross-frequency coupling focuses on coupling within brain regions or between a small number of regions of interest, rather than the entire connectome. Only a handful of studies have demonstrated that cross-frequency coupling also occurs in whole brain functional networks [@keiteletal_VisualCortexResponses_2017; @siebenhuhneretal_CrossfrequencySynchronizationConnects_2016; @palva_PhaseSynchronyNeuronal_2005; @vandermeijetal_PhaseAmplitudeCouplingHuman_2012], and the validity of these findings has recently come into question due to standard cross-frequency coupling analyses showing significant cross-frequency coupling in the absence of any underlying physiological coupling [@aruetal_UntanglingCrossfrequencyCoupling_2015]. Recently, however, @siebenhuhneretal_GenuineCrossfrequencyCoupling_2020 were able to demonstrate the presence of true cross-frequency coupling in whole brain functional networks---ruling out the influence of spurious coupling---in both a small sample of presurgical epilepsy patients during eyes-closed resting state using stereo-EEG, and a small sample of healthy controls during eyes-open resting state using magnetoencephalography. Moreover, they found that network strength was predictive of individual differences on several cognitive tasks in the healthy control sample (the other sample did not complete these tasks); thus, cross-frequency coupling may be a worthwhile avenue for future EEG network variant research if methods for estimating true cross-frequency coupling are validated, improved, and made more accessible [e.g., @idajietal_HarmoniMethodEliminating_2022].

Finally, we note that our approach to estimating individual differences in functional connectome similarity within and between participants was somewhat insensitive to the possibility that EEG network variants are not individually unique, but rather fall into unique subgroups or clusters. This was due to our use of pairwise contrasts comparing the degree of similarity within versus between participants, which would necessarily lead to larger effect sizes in cases where a participant's functional connectomes were wholly unique versus cases where a participant's functional connectomes were similar to some participants but different from others. Thus, in some cases individual effect sizes may have been reduced as a consequence not of a group effect, but of a subgroup effect. Given this possibility, we emphasize the importance of evaluating outcome variability estimates in our sample in light of the patterns present in the similarity matrix those estimates were based on. One potential solution to control for possible subgroup effects in future studies using a pairwise contrast approach would be to add a *within subgroup* covariate to the model (denoting whether a pair came from the same or different subgroups), which could be derived from cluster analysis of functional connectome data [e.g., @tokudaetal_MultipleClusteringIdentifying_2021]. Additionally, using more diverse and/or larger samples may further reduce the likelihood of possible subgroup effects skewing individual effect sizes towards zero, and improve the precision of uncertainty estimates for individual-level sub-models, reducing the likelihood of the data not resolving whether the most compatible effect sizes for a given individual are positive or negative.

<!--

Add a limitation to the discussion about how differences in connectivity could be caused by actual differences in strength, or differences in topography of functional areas like kraus discuss for fMRI, but for EEG:

>“Thus, typical estimates of fcMRI strength are not able to dissociate whether the observed results are due to individual differences in the spatial extent of brain networks or the degree of functional coupling between analogous regions.” ([Kraus et al., 2023, p. 11](zotero://select/library/items/VMKRITWL)) ([pdf](zotero://open-pdf/library/items/DRP597AH?page=11&annotation=VBNZ33YQ))

<!-- For example, in a given individual, variation in connectivity strength may cause canonical network nodes to be partitioned out of a network they are typically associated with in group-averaged models or be incorporated into a different network when using community detection algorithms [@bijsterboschetal_ChallengesFutureDirections_2020; @dworetskyetal_ProbabilisticMappingHuman_2021; @gordonnelson_ThreeTypesIndividual_2021; @uddinetal_ControversiesProgressStandardization_2023]; variation in the size and position of network nodes may cause canonical network nodes to appear absent or disconnected when using standardized parcellation schemes due to localization errors [@chongetal_IndividualParcellationResting_2017; @dworetskyetal_TwoCommonDistinct_2021; @gordonetal_IndividualVariabilitySystemLevel_2017; @gordonnelson_ThreeTypesIndividual_2021; @uddinetal_ControversiesProgressStandardization_2023]; and variation in network topography may create distinct topological features (e.g., extra network nodes) that are not typically present in group-averaged models [@dworetskyetal_TwoCommonDistinct_2021; @kongetal_SpatialTopographyIndividualSpecific_2019; @glasseretal_MultimodalParcellationHuman_2016; @gordonnelson_ThreeTypesIndividual_2021; @laumannetal_FunctionalSystemAreal_2015; @seitzmanetal_TraitlikeVariantsHuman_2019; @uddinetal_ControversiesProgressStandardization_2023]. However, because each of these forms of variation can be present simultaneously, the effects of one form of variation can influence estimates of the others; thus making it unclear whether a deviation from the mean was driven by connectional, spatial, or topographical variation  [@gordonnelson_ThreeTypesIndividual_2021]. -->

<!--
>“Each of these forms of variation is important to consider when building or applying a taxonomy of large-scale brain networks, and emphasizes the value of employing individual-level network definitions. In a given individual, variation in functional connectivity strength may result in a canonical network node to “fall out” of the network or be incorporated into a different network. Spatial variation in networks may create the appearance that a network node is absent or disconnected when it is actually mis-localized by standardized parcellation schemes. Topographical variations may create apparent extra network nodes not typically present in most individuals. Any taxonomy must reflect the central tendency network characteristics of the general population, but also be flexible enough to accommodate connectional, spatial, and topographical variations found across individuals.” ([Uddin et al., 2023, p. 881](zotero://select/library/items/AJMLVVBY))






Because each of these forms of interindividual variability can be present simultaneously, an open question is which of these contribute more...

>Overall, spatial variation appears to contribute more to individual differences in brain networks than variations in connectivity strength (Bijsterbosch et al., 2019).

However, @grattonetal_FunctionalBrainNetworks_2018 found that ..., suggesting that interindividual variability in connectivity strength does not arise entirely from differences in the anatomical distribution of networks across individuals but may reflect differences across individuals in the magnitude of connectivity within and between networks.

>“Soon we came to realize that, rather than there being a single type of variation in FC that differs across individuals on a single axis, there are at least three separate, independent types of individual variation in FC networks that, unfortunately, each confound attempts to estimate the other two types of variation.” ([Gordon and Nelson, 2021, p. 80](zotero://select/library/items/8MH843XX)) ([pdf](zotero://open-pdf/library/items/6GA7FEUR?page=2&annotation=X8WUVLNL))

>“We also observed that RSFC measures were highly subject-specific: session-to-session similarities were high within subject but much lower across subjects (Figure 2H). Similar findings have been reported by others as the basis for connectivity-based ‘fingerprinting’ of individuals (Anderson et al., 2011; Finn et al., 2015; Miranda-Dominguez et al., 2014; Pannunzi et al., 2017; Xu et al., 2016). However, the ability to distinguish subjects may at least in part be explained by differences in the spatial locations of brain networks across individuals (Gordon et al., 2017a; Laumann et al., 2015; Satterthwaite and Davatzikos, 2015). Additionally, systematic differences in other unconstrained biological (e.g., brain size, gyral folding patterns) or non-biological factors (e.g., data quality) may contribute to subject discrimination.” ([Gordon et al., 2017, p. 10](zotero://select/library/items/JM7K9R6L)) ([pdf](zotero://open-pdf/library/items/4CSMSVVH?page=10&annotation=CXQV5P2Z))

<!-- Furthermore, the magnitude of these differences only slightly diminishes when using individually optimized parcels (matched at the network level) rather than group parcels, suggesting that interindividual variability in connectivity strength does not arise entirely from differences in the anatomical distribution of networks across individuals but may reflect differences across individuals in the magnitude of connectivity within and between networks.

>"Furthermore, examining the similarity of networks composed of individually optimized, rather than group, parcels (matched at the network level) only slightly diminishes individual effects in favor of group similarity (Figure S7). This observation suggests that individual effects do not arise entirely from differences in the anatomical distribution of networks across individuals but may reflect differences across individuals in the magnitude of connectivity within and between networks. Future work adopting hyper-alignment (Guntupalli et al., 2016; Guntupalli and Haxby, 2017) or related techniques may help to clarify the contribution of individual differences in spatial mapping from differences in connectivity magnitude." @finnetal_FunctionalConnectomeFingerprinting_2015
-->

<!-- First, we assumed that five minute recordings would be sufficient to get stable functional connectivity estimates with EEG given that (1) the longer scanning times needed to reliably detect network variants with fMRI is considered a consequence of its infraslow sampling rate [@seitzmanetal_TraitlikeVariantsHuman_2019], rather than a consequence of the timeframe of the neural processes we are interested in; and (2) EEG samples a substantially larger number of data points than fMRI in a much shorter timeframe. Additionally, we assumed that the connectivity structure in each frequency band was stationary over the length of the recording for both phase and amplitude coupling functional connectomes. Although neural oscillations are naturally non-stationary, varying from moment to moment [@faisaletal_NoiseNervousSystem_2008], stationary patterns of functional connectivity during resting state have been identified in EEG [e.g., @olguin-rodriguezetal_CharacteristicFluctuationsStable_2018], fMRI [e.g., @laumannetal_StabilityBOLDFMRI_2017], and simultaneous EEG-fMRI studies [e.g., @danielarzate-menaetal_StationaryEEGPattern_2022], with consistent positive or negative coupling occurring between sites or electrodes, even when averaging over multiple epochs. These stationary patterns are thought to be the substrate for effective brain function, permitting the adaptability and efficiency needed to optimize responses to our often unpredictable environment [@garrettetal_MomenttomomentBrainSignal_2013], and thus reflect neuropsychologically relevant signals of interest. However, we do note that approaches accounting for nonlinear dynamics may provide complimentary insights to those that focus on the stable aspects of network variants [e.g., @vandevilleetal_WhenMakesYou_2021]. -->

<!-- Our choice to only use resting state data may have also influenced our results. Although resting state data provides a good representation of intrinsic brain activity [@raichle_TwoViewsBrain_2010], ...,  -->

<!-- Previous fMRI and EEG studies have found that averaging over different tasks leads to more stable individual differences... -->

<!-- Discuss dimensionality reduction for measuring similarity -->

<!-- ## Future directions -->

<!-- It is likely that the field of EEG connectomics will follow similar research trends and advances as have happened in the fMRI connectomics field.  -->

<!-- ## Implications for future research -->

<!-- The main implication of our findings is that---if EEG network variants do exist---there is no guarantee that their presence can be detected in a given individual or data set, given the background model.  -->

<!-- This is a particularly salient point for researchers who are interested in network variants for clinical and other applied purposes... -->

<!-- This is a particularly salient point for future research interested in network variants as biomarkers  -->

<!-- seeking to develop neuroimaging-based biomarkers with real-world utility in areas such as biometrics (H.-L. Chan, Kuo, Cheng, & Chen, 2018) and human lifespan development (Garrett et al., 2013) -->

<!-- There is evidence to suggest EEG network variants do exist. Discuss fingerprinting and phenotyping studies... -->

<!-- Systematic investigation into the factors that influence the detection of EEG network variants... preprocessing, how volume conduction is dealt with, whether between-person differences are sensitive to timescale or task, choice of connectivity measure, method of comparing functional connectomes, etc. -->

## Conclusion

In this study, we explored the feasibility of using EEG to study network variants. We found at most weak supportive evidence for the presence of network variants in a subset of our sample for phase coupling functional connectomes in the theta, alpha, beta, and gamma bands, but did not generally demonstrate the feasibility of using EEG to study network variants given the inconsistencies observed across participants. In future studies, it would be interesting to see whether network variants in EEG functional connectomes can be made more consistent through state or task manipulations that are known to bring out meaningful differences between participants [@finn_ItTimePut_2021; @finnetal_CanBrainState_2017; @finnetal_IdiosynchronySharedResponses_2020; @finnbandettini_MoviewatchingOutperformsRest_2020]; or to systematically investigate how decisions related to preprocessing or functional connectivity estimation influence the structure of EEG functional connectomes and their similarity within and between individuals, across tasks, states, and over time [@colcloughetal_HowReliableAre_2016; @fraschinietal_RobustnessFunctionalConnectivity_2019].

<!-- Footnotes start --------------------------------------------------------->

[^9]: EEG biometrics research has demonstrated that resting state (eyes open and closed) functional connectomes from the same individual can be accurately matched when comparing a given individual's connectome against all other connectomes in small samples [up to and around 100 participants\; e.g., @laroccaetal_HumanBrainDistinctiveness_2014]. However, although findings like this do suggest that EEG functional connectomes are more similar within than between individuals---to a degree that allows for accurate matching---they do not address the magnitude of these individual differences. Thus, future work may find that EEG has sufficient spatial resolution for biometrics (where the size of individual differences do not matter, so long as they are consistent), but insufficient spatial resolution for studying network variants (where the size of individual differences are a focal interest).

<!-- Footnotes end ----------------------------------------------------------->
